before_commands:
    - 'composer install --prefer-source --no-interaction --dev'
filter:
    paths:
        - 'src/*'
    excluded_paths:
        - 'build/*'
        - 'vendor/*'
        - 'tests/*'
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
checks:
    php:
        return_doc_comments: true
        simplify_boolean_return: true
        uppercase_constants: true
        return_doc_comment_if_not_inferrable: true
        properties_in_camelcaps: true
        phpunit_assertions: true
        parameters_in_camelcaps: true
        parameter_doc_comments: true
        no_short_variable_names:
            minimum: '6'
        no_short_method_names:
            minimum: '10'
        no_goto: true
        newline_at_end_of_file: true
        line_length:
            max_length: '120'
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: false
        classes_in_camel_caps: true
        avoid_todo_comments: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_fixme_comments: true
        align_assignments: true
tools:
    php_analyzer: true
    php_mess_detector: true
    php_code_sniffer:
        config:
            standard: PSR2
    php_code_coverage:
        config_path: phpunit.xml
    php_cpd:
        excluded_dirs:
            - vendor
            - tests
    php_loc:
        excluded_dirs:
            - vendor
            - tests
    php_pdepend:
        excluded_dirs:
            - vendor
            - tests
    php_sim: true
